apiVersion: v1
kind: List
items:
- kind: Namespace
  apiVersion: v1
  metadata:
    name: kube-sleepschedule
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-sleepschedule
  namespace: kube-sleepschedule
data:
  # downscale for non-work hours
  DEFAULT_DOWNTIME: "SAT-SUN 00:00-24:00 US/Central,Fri-Fri 20:00-24:00 US/Central"
#DEFAULT_DOWNTIME="Sat-Sun 00:00-24:00 US/Central,Fri-Fri 20:00-24:00 US/Central'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-sleepschedule
  namespace: kube-sleepschedule
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-sleepschedule
  namespace: kube-sleepschedule
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - watch
  - list
  - update
  - patch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - watch
  - list
  - update
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - watch
  - list
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-sleepschedule
  namespace: kube-sleepschedule
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-sleepschedule
subjects:
- kind: ServiceAccount
  name: kube-sleepschedule
  namespace: kube-sleepschedule
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    application: kube-sleepschedule
  name: kube-sleepschedule
  namespace: kube-sleepschedule
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-sleepschedule
  template:
    metadata:
      labels:
        application: kube-sleepschedule
    spec:
      serviceAccountName: kube-sleepschedule
      containers:
      - name: sleepschedule
        image: hjacobs/kube-downscaler:19.10.1
        args:
          # dry run by default, remove to perform downscaling
          #- --dry-run
          # run every minute
          - --interval=60
          - --grace-period=300
          - --exclude-namespaces=kube-system,kube-sleepschedule
          # - --exclude-deployments=
        envFrom:
          - configMapRef:
              name: kube-sleepschedule
              optional: true
        resources:
          limits:
            cpu: 10m
            memory: 100Mi
          requests:
            cpu: 5m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
